#CS 403/603 Machine Learning

##Lab: 08-01-2021

In [1]:
import matplotlib.pyplot as plt 
plt.style.use('ggplot')
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd  
import seaborn as sns 
plt.rcParams['figure.figsize'] = (12, 8)

In [37]:
X = np.array([[2104, 5,10],[1416, 3,6],[1534, 3,6]], dtype=np.float64)
X

array([[2104.,    5.,   10.],
       [1416.,    3.,    6.],
       [1534.,    3.,    6.]])

In [38]:
y = np.array([460, 232, 315], dtype=np.float64)
y = y[:,np.newaxis]

In [41]:
y.shape

(3, 1)

In [6]:
print(np.shape(X))

(3, 3)


In [39]:
ones = np.ones((X.shape[0], 1))
X = np.hstack((ones, X))

In [40]:
X

array([[1.000e+00, 2.104e+03, 5.000e+00, 1.000e+01],
       [1.000e+00, 1.416e+03, 3.000e+00, 6.000e+00],
       [1.000e+00, 1.534e+03, 3.000e+00, 6.000e+00]])

Ypredict = X.Theta




In [35]:
def Ypredict(X, theta):
  return np.dot(X, theta)

# Closed Form

Getting the theta

In [36]:
def closedfrom(X,Y):
  Y = np.mat(Y)
  theta_1 = np.dot(X.T, X)
  theta_2 = np.dot(X.T, Y)

  #theta = np.linalg.inv(theta_1)* (theta_2)
  theta = np.linalg.pinv(theta_1).dot(theta_2)
  return theta

In [42]:
theta = closedfrom(X, y)
print(theta)

[[-380.10169484]
 [   0.70338983]
 [ -25.59322033]
 [ -51.18644066]]


As we can see the result here: we can not the theta. In our Dataset two features are linearly dependent hence the design matrix becomes singular that is non invertible, so in this case we can use the concept of pseudo inverse.

In [43]:
y_predict =Ypredict(X,theta)

In [44]:
error = y-y_predict
error

matrix([[ 2.30784281e-09],
        [-9.34005584e-09],
        [ 5.06997822e-09]])