#CS 403/603 Machine Learning

##Lab: 08-01-2021

In [1]:
import matplotlib.pyplot as plt 
plt.style.use('ggplot')
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd  
import seaborn as sns 
plt.rcParams['figure.figsize'] = (12, 8)

In [3]:
X = np.array([[2104, 5],[1416, 3],[1534, 3]])
X

array([[2104,    5],
       [1416,    3],
       [1534,    3]])

#Normalizing the Dataset

In [4]:
X = (X-X.mean())/X.std()
X

array([[ 1.45321856, -0.96797929],
       [ 0.65961012, -0.97028629],
       [ 0.7957232 , -0.97028629]])

In [5]:
y = np.array([460, 232, 315])
Y = y[:,np.newaxis]

In [6]:
Y.shape

(3, 1)

In [7]:
print(np.shape(X))

(3, 2)


In [8]:
ones = np.ones((X.shape[0], 1))
Design_X = np.hstack((ones, X))

In [9]:
Design_X

array([[ 1.        ,  1.45321856, -0.96797929],
       [ 1.        ,  0.65961012, -0.97028629],
       [ 1.        ,  0.7957232 , -0.97028629]])

Ypredict = X.Theta


In [10]:
def Ypredict(X, theta):
  return np.dot(X, theta)

# Closed Form

Getting the theta

In [11]:
def closedfrom(X,Y):
  Y = np.mat(Y)
  theta_1 = np.dot(X.T, X)
  theta_2 = np.dot(X.T, Y)

  #theta = np.linalg.inv(theta_1)* (theta_2)
  theta = np.linalg.pinv(theta_1)* (theta_2)
  return theta

In [12]:
theta = closedfrom(Design_X, Y)
print(theta)


[[-107811.04149714]
 [    609.78711622]
 [-110937.17439822]]


In [14]:
y_predict =Ypredict(Design_X,theta)

In [19]:
error = Y-y_predict
error

matrix([[3.18325760e-07],
        [3.95555389e-07],
        [1.64069093e-07]])

In [20]:
theta.shape

(3, 1)

In [21]:
y_predict.shape

(3, 1)