CS 403/ CS 603, Machine Learning


Lab: 08-01-2021


Closed form Linear Regression

In [1]:
import matplotlib.pyplot as plt 
plt.style.use('ggplot')
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd  
import seaborn as sns 
plt.rcParams['figure.figsize'] = (12, 8)

In [3]:
X = np.array([[2104, 5],[1416, 3],[1534, 3]], dtype=np.float64)

In [4]:
y = np.array([460, 232, 315], dtype=np.float64)

In [5]:
y = y[:,np.newaxis]

In [6]:
y.shape

(3, 1)

In [7]:
print(np.shape(X))

(3, 2)


In [8]:
X

array([[2104.,    5.],
       [1416.,    3.],
       [1534.,    3.]])

In [9]:
ones = np.ones((X.shape[0], 1))
X = np.hstack((ones, X))

In [10]:
print(X.shape)
X

(3, 3)


array([[1.000e+00, 2.104e+03, 5.000e+00],
       [1.000e+00, 1.416e+03, 3.000e+00],
       [1.000e+00, 1.534e+03, 3.000e+00]])

Ypredict = X.Theta

In [11]:
def Ypredict(X, theta):
  return np.dot(X, theta)

# Closed Form

Getting the theta

In [27]:
def closedfrom(X,Y):
  Y = np.mat(Y)
  theta_1 = np.dot(X.T, X)
  theta_2 = np.dot(X.T, y)

  #If our matrix is not invertible we can use pseudo inverse.(Question 2)
  theta = np.linalg.pinv(theta_1).dot(theta_2)
  return theta

In [28]:
theta = closedfrom(X, y)
print(theta)

[[-380.10169491]
 [   0.70338983]
 [-127.96610169]]


In [36]:
y_predict =Ypredict(X,theta)
y_predict

array([[460.],
       [232.],
       [315.]])

In [37]:
error = y-y_predict
error

array([[ 2.94221536e-10],
       [-5.01586328e-10],
       [ 9.09494702e-11]])